### ISSUE TITLE
None Reobfing of Jar

### ISSUE THREAD

**Issue by AterAnimAvis** [TonimatasMCDEV/KrystalCraft#11]
Your cleanup gradle commit https://github.com/TonimatasDEV/KrystalCraft/commit/64a7f9ce8017f1034c95d1ef0ea06a33ce14244f removed the line `jar.finalizedBy('reobfJar')` , unless you build via `reobfJar` your built jar isn't getting reobfuscated for usage in a non Development Environment.

This can be seen in your latest release <https://www.curseforge.com/minecraft/mc-mods/krystalcraft/files/4574480>.
Trying to run this in a normal Minecraft Client will result in a
`java.lang.NoSuchMethodError: 'net.minecraft.world.level.block.state.BlockBehaviour$Properties net.minecraft.world.level.block.state.BlockBehaviour$Properties.of()'`
due to the lack of Reobfuscation.

Also in the same commit your changed to not using `fg.deobf` for your Mod Dependencies, this is actually required.
<https://forge.gemwire.uk/Dependencies#Deobfuscating_Dependencies>

**Comment by TonimatasDEV** [comment]
Thanks you
