### ISSUE TITLE
can't craft cutting station on fabric

### ISSUE THREAD

**Issue by pfgithub** [TonimatasMCDEV/KrystalCraft#15]
https://github.com/TonimatasDEV/KrystalCraft/blob/52dd20f2be1d582549f9c7b489929a5c5ad2ba14/fabric/src/main/resources/data/krystalcraft/recipes/cutting_station.json#L16

this tag doesn't seem to exist. in EMI the recipe shows as this but then it can't be crafted

![image](https://github.com/TonimatasDEV/KrystalCraft/assets/6010774/0d774dea-01ae-4500-b2f8-73a57b627656)

**Comment by ColdStoneSys** [comment]
This is an issue again on 1.20.1 version 0.0.4.3
![Screenshot 2024-09-01 110412](https://github.com/user-attachments/assets/c7c9dda4-4a0d-4bbc-8942-839e97498a0e)

**Comment by TonimatasDEV** [comment]
@Pinkietron It works fine: 
![image](https://github.com/user-attachments/assets/63018b56-007c-42a5-981b-f6a0a258ddc3)

**Comment by ColdStoneSys** [comment]
Then the EMI/JEI/REI recipe fill needs to be updated because it does not show the raw diamond in the recipe

![image](https://github.com/user-attachments/assets/730b1427-d53d-4ffd-a076-13afded1b384)
