### ISSUE TITLE
Vanilla ore can't be mined

### ISSUE THREAD

**Issue by DayIsGone** [TonimatasMCDEV/KrystalCraft#2]
with your mod installed installed anything that takes iron+ (tried redstone, diamond and game lapis even with a diamond and netherrite pick) to break will break and give xp but not the ore.  anything that can be gotten with a lesser pick and the ores from the mod work perfectly

https://youtu.be/Qe8kYr0eihw

I am using forge 41.0.38 if that matters

**Comment by TonimatasMCDEV** [comment]
> with your mod installed installed anything that takes iron+ (tried redstone, diamond and game lapis even with a diamond and netherrite pick) to break will break and give xp but not the ore. anything that can be gotten with a lesser pick and the ores from the mod work perfectly
> 
> https://youtu.be/Qe8kYr0eihw
> 
> I am using forge 41.0.38 if that matters

**Comment by TonimatasDEV** [comment]
> with your mod installed installed anything that takes iron+ (tried redstone, diamond and game lapis even with a diamond and netherrite pick) to break will break and give xp but not the ore. anything that can be gotten with a lesser pick and the ores from the mod work perfectly
> 
> https://youtu.be/Qe8kYr0eihw
> 
> I am using forge 41.0.38 if that matters

I am uploading a new version, this bug is fixed in the new update.

**Comment by TonimatasDEV** [comment]
> > with your mod installed installed anything that takes iron+ (tried redstone, diamond and game lapis even with a diamond and netherrite pick) to break will break and give xp but not the ore. anything that can be gotten with a lesser pick and the ores from the mod work perfectly
> > https://youtu.be/Qe8kYr0eihw
> > I am using forge 41.0.38 if that matters
> 
> I am uploading a new version, this bug is fixed in the new update.

https://www.curseforge.com/minecraft/mc-mods/krystalcraft/files/3840862
