### ISSUE TITLE
KrystalCraft version 0.0.3.3 failing to load

### ISSUE THREAD

**Issue by Gamemassa** [TonimatasMCDEV/KrystalCraft#9]
Minecraft version: 1.19.2
Forge version: 43.1.3
KrystalCraft version: 0.0.3.3

The latest version of KrystalCraft returns a loading error with the latest versions of Forge and Minecraft.

Crash Report:
https://gist.github.com/Gamemassa/6419df689a6d46b524ba56a882204c67

**Comment by TonimatasDEV** [comment]
Wait to the new version

**Comment by TonimatasDEV** [comment]
Test this version: https://www.curseforge.com/minecraft/mc-mods/krystalcraft/files/4017314
